### ISSUE TITLE
Sfpdfviewer xamarin forms freetext is not saved

### ISSUE THREAD

**Issue by febryanadip96** [syncfusion/xamarin-demos#12]
I try to save file pdf after i added a freetext, but, freetext is not saved in pdf

**Comment by ramkumarravy** [comment]
Hi @febryanadip96 ,

Greetings from Syncfusion.

We have confirmed that the issue “Freetext is not preserved after saving” is a defect and logged defect report for this issue. The fix for the same will be included in our upcoming weekly NuGet release and it is expected to be available on 23 July, 2019.

For any further queries, please create a new incident (under your account) from our support website to provide solution quickly. Please find the support website link from below.

https://www.syncfusion.com/support/directtrac/incidents/newincident  

Regards,
Ramkumar
(I work for Syncfusion Software)

**Comment by ramkumarravy** [comment]
Hi @febryanadip96 ,

As promised earlier, we have fixed the issue “Freetext is not preserved after saving” and the fix is published in our 2019 Vol 2 weekly NuGet release with version 17.2.0.36. Kindly update your SfPdfViewerControl with the mentioned version to get the issue resolved.  

Regards,
Ramkumar
