### ISSUE TITLE
Sfpdfviewer xamarin forms ios freetext color cannot be changed

### ISSUE THREAD

**Issue by febryanadip96** [syncfusion/xamarin-demos#13]
i try to change freetext color in ios, in app it's changed, but color is still black after i open saved file

**Comment by Balasubramanian93** [comment]
Hi @febryanadip96 ,

Greetings from Syncfusion!!

We have tried to reproduce the issue “Color of the free text annotation is not preserved” on saving and loading the PDF document in SfPdfViewer in Xamarin.Forms.iOS, but it is working fine as expected. Kindly refer the sample in the attachment which we created to reproduce the reported issue.
 
Kindly share the following details to analyze more on this issue and it will be helpful for us to analyze more on this issue.
1.	Modify / Simple sample with which the issue could be reproduced.
2.	Replication procedure to reproduce the issue or screen shot illustrating the issue.
3.	PDF document with which the issue could be reproduced.

Thanks,
Balasubramanian S
( I work for Syncfusion )

[Sample.zip](https://github.com/syncfusion/xamarin-demos/files/3406779/Sample.zip)

**Comment by Balasubramanian93** [comment]
Hi @febryanadip96 ,

Thank you for your patience.
 
On further analyzing the issue, we could reproduce the issue “Color of the free text annotation is not preserved while saving the PDF document” in SfPdfViewer in Xamarin.Forms.iOS on viewing the saved PDF document in **macOS previewer**. So, we have confirmed this issue is a defect and the fix for this issue will be included in our Weekly NuGet published under nuget.org and it is expected to be available on 30th July 2019. 

We will let you know once the Weekly NuGet is published.

Thanks, 
Balasubramanian S
(I work for Syncfusion Software)

**Comment by Balasubramanian93** [comment]
Hi @febryanadip96 ,

As promised earlier, we have fixed the issue “Freetext is not preserved after saving” and the fix is published in our 2019 Vol 2 weekly NuGet release with version 17.2.0.40. Kindly update your SfPdfViewerControl with the mentioned version to get the issue resolved. 

Regards,
Balasubramanian
(I work for Syncfusion Software)
