### ISSUE TITLE
SfPdfViewer cannot open HyperLinks when targeting Android SDK 33

### ISSUE THREAD

**Issue by ironsm4sh** [syncfusion/xamarin-demos#56]
New apps on Google Play _must_ target Android 13 (API level 33) [[1]](https://developer.android.com/google/play/requirements/target-sdk)

Setting the target SDK to 33 defined in `/Android/SampleBrowser/Properties/AndroidManifest.xml` 
```diff
 ﻿<?xml version="1.0" encoding="utf-8"?>
 <manifest xmlns:android="http://schemas.android.com/apk/res/android" android:versionCode="1" android:versionName="16.1" package="XamarinAndroid.SampleBrowser" android:installLocation="auto">
-       <uses-sdk android:minSdkVersion="21" android:targetSdkVersion="29"/>
+       <uses-sdk android:minSdkVersion="21" android:targetSdkVersion="33" />
        <application android:label="Syncfusion Components for Xamarin.Android" android:largeHeap="true">
```

Is done as shown above, however, Android is no longer able to open any Hyperlinks in the PDFViewer example.

<details>
  <summary>Android PDFViewer screenshot</summary>

![screenshot](https://github.com/syncfusion/xamarin-demos/assets/23172578/fa5b2ce1-48a5-4f68-97ce-04ec96c5b3ce)
</details>

It still shows the dialog just fine, but choosing `Open` only closes the dialog without opening the web browser. How do I allow the user to open hyperlinks?

**Comment by ironsm4sh** [comment]
A semi-functional workaround can be created by adding the following event handler.
```csharp
pdfViewerControl.HyperlinkClicked += (object sender, HyperlinkClickedEventArgs args) => {
    var uri = Android.Net.Uri.Parse(args.Uri);
    context.StartActivity(new Intent(Intent.ActionView, uri));
};
```

This allows the user to open Hyperlinks, but the dialog is bypassed while still shown. This is unsuitable for use in production.

**Comment by manojSF3414** [comment]
Hi ironsm4sh,


We are glad to announce that our Essential Studio 2023 Volume 4 Service Pack release v24.2.3 is rolled out and is available for download under the following link.


[Essential Studio 2023 Volume 4 Service Pack Release v24.2.3 is available for download | Announcements Forums | Syncfusion](https://www.syncfusion.com/forums/186513/essential-studio-2023-volume-4-service-pack-release-v24-2-3-is-available-for-download)

 

We have resolved the issue "Cannot open Hyperlinks on the browser when targeting Android SDK 33" and the fix is available with this release.

 

We thank you for your support and appreciate your patience in waiting for this release. Please get in touch with us if you would require any further assistance.
